### ISSUE TITLE
Asking about BART-based Generator

### ISSUE THREAD

**Issue by JudePark96** [zhongwanjun/CARP#1]
Hi! Thanks for your nice work!

I want to reproduce your experiment setting on Korean Dataset for my study.
Can you release the Bart-based Generator ?

Best,
Thanks!

**Comment by zhongwanjun** [comment]
We will further complete the code before the IJCAI conference.  Or you can try to use the standard text generation pipeline (using T5/BART) from Transformers(huggingface) library, which can also work.

**Comment by JudePark96** [comment]
Thanks for your reply! I will close this issue!
